[package]
name = "one_billion_row_challenge_polars"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.36.2", features = ["lazy", "describe", "concat_str", "strings", "round_series"]}